package com.retrofit.android.retrofitdemo.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CATALOGS".
 */
@Entity
public class Catalogs {

    @Id(autoincrement = true)
    private Long id;

    @Index
    private String name;
    private Integer key;
    private String value;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Catalogs() {
    }

    public Catalogs(Long id) {
        this.id = id;
    }

    @Generated
    public Catalogs(Long id, String name, Integer key, String value) {
        this.id = id;
        this.name = name;
        this.key = key;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getKey() {
        return key;
    }

    public void setKey(Integer key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
